export type FaqItem = {
  answer: string;
  category: string;
  id: string;
  question: string;
  rulesId: string;
};

export const FAQ_CATEGORIES = [
  "Getting Started",
  "Free Trial",
  "Evaluation",
  "Trading",
  "Funded Accounts",
  "Payouts",
  "Fair Play & Security",
  "Billing",
] as const;

export const FAQ_ITEMS: readonly FaqItem[] = [
  {
    id: "what-is-levli",
    category: "Getting Started",
    question: "What is Levli?",
    answer: "Levli is a crypto prop trading platform built around a simulated skill evaluation. Traders who pass can receive a simulated funded account and become eligible for discretionary performance-based rewards paid in USDC from company revenue.",
    rulesId: "how-it-works",
  },
  {
    id: "deposit-capital",
    category: "Getting Started",
    question: "Do I need to deposit trading capital?",
    answer: "No. You never deposit trading capital. You pay a one-time evaluation fee for access to a simulated account. The evaluation fee is refunded with your first approved payout; reset fees are not refunded.",
    rulesId: "account-sizes",
  },
  {
    id: "sign-up",
    category: "Getting Started",
    question: "How do I sign up?",
    answer: "Connect a supported crypto wallet and complete the eligibility confirmations. Identity or recipient information may be requested later when required for payout or compliance review.",
    rulesId: "simulation",
  },
  {
    id: "kyc",
    category: "Getting Started",
    question: "Do I need to complete KYC?",
    answer: "Identity verification is not part of the initial simulated-trading setup, but it may be required before a payout and whenever applicable sanctions, identity, or recipient-information checks require it. The exact requirement is shown before you submit.",
    rulesId: "payouts",
  },
  {
    id: "restricted-countries",
    category: "Getting Started",
    question: "Which countries are restricted?",
    answer: "Levli is not available to residents of restricted jurisdictions, including the United States, the United Kingdom, and sanctioned jurisdictions. Confirm your residence at signup and review the Terms of Use for the current list.",
    rulesId: "simulation",
  },
  {
    id: "real-trading",
    category: "Getting Started",
    question: "Is this real trading?",
    answer: "No. Trial, Evaluation, and Funded accounts are simulated. Prices reference real-time market data, but orders are filled by Levli's simulation engine and are never routed to an exchange. Eligible payouts are real performance-based rewards paid from company revenue in USDC.",
    rulesId: "simulation",
  },
  {
    id: "trial-how",
    category: "Free Trial",
    question: "How does the Free Trial work?",
    answer: "It is a free $10,000 simulated account that runs for 7 days with the same core rules as a paid Evaluation. Each person can use one Free Trial.",
    rulesId: "free-trial",
  },
  {
    id: "trial-funded",
    category: "Free Trial",
    question: "If I pass the Trial, do I get funded?",
    answer: "No. The Trial is a rehearsal, not a shortcut. To become eligible for a simulated funded account, you must pass a paid Evaluation and complete the applicable review.",
    rulesId: "free-trial",
  },
  {
    id: "trial-end",
    category: "Free Trial",
    question: "What happens when my Trial ends?",
    answer: "The Trial expires after 7 days. It cannot be extended or repeated on the same user profile.",
    rulesId: "free-trial",
  },
  {
    id: "time-to-pass",
    category: "Evaluation",
    question: "How long do I have to pass?",
    answer: "There is no time limit. Keep trading until the profit target, consistency requirement, and zero-open-position condition are satisfied at the same time.",
    rulesId: "passing",
  },
  {
    id: "pass-one-day",
    category: "Evaluation",
    question: "Can I pass in a single day?",
    answer: "You can reach the 10% target quickly, but no single day may make up more than 35% of total realized profit at the moment you pass. In practice, satisfying consistency requires profit across at least three days.",
    rulesId: "consistency",
  },
  {
    id: "pass-requirements",
    category: "Evaluation",
    question: "What exactly do I need to pass?",
    answer: "All three conditions must hold together: realized profit of at least 10%, best day at or below 35% of total realized profit, and zero open positions.",
    rulesId: "passing",
  },
  {
    id: "consistency-break",
    category: "Evaluation",
    question: "What happens if I break the Consistency Rule?",
    answer: "It is not an account violation. Your pass remains pending. Continue trading and increase total realized profit until your best day returns to 35% or less of the total.",
    rulesId: "consistency",
  },
  {
    id: "unrealized-target",
    category: "Evaluation",
    question: "Does unrealized profit count toward the target?",
    answer: "No. Only closed, realized PnL counts toward the profit target. Drawdown is measured on equity, so unrealized losses do count against the risk limits.",
    rulesId: "profit-target",
  },
  {
    id: "dd-vs-daily",
    category: "Evaluation",
    question: "What's the difference between Max Drawdown and Daily Loss?",
    answer: "Max Drawdown is a 6% static floor that ends the account if equity touches it. Daily Loss is a 4% circuit breaker that auto-closes positions and pauses trading until the next UTC day; the account survives.",
    rulesId: "daily-loss",
  },
  {
    id: "floor-move",
    category: "Evaluation",
    question: "Does the drawdown floor move up as I profit?",
    answer: "No. It stays fixed at initial capital × 0.94. Profits increase the distance between current equity and that fixed floor.",
    rulesId: "max-drawdown",
  },
  {
    id: "failed-reset",
    category: "Evaluation",
    question: "I failed. Can I try again?",
    answer: "Yes. An Evaluation can be reset once within 7 days of failure at the reset price. A reset creates a new account at full initial capital. You can also purchase a new Evaluation.",
    rulesId: "resets",
  },
  {
    id: "evaluation-limit",
    category: "Evaluation",
    question: "Is there a limit on how many Evaluations I can run?",
    answer: "There is no fixed Evaluation count limit. The combined active funded allocation limit is $200,000 per trader.",
    rulesId: "funded-rules",
  },
  {
    id: "markets",
    category: "Trading",
    question: "Which markets can I trade?",
    answer: "Crypto perpetual futures. The available symbols, leverage limits, and configured simulated fees are shown in the trading interface.",
    rulesId: "leverage",
  },
  {
    id: "leverage",
    category: "Trading",
    question: "What leverage do I get?",
    answer: "Leverage is configured per symbol and displayed before order submission. Orders over the displayed limit are rejected without an account penalty.",
    rulesId: "leverage",
  },
  {
    id: "overnight-weekend",
    category: "Trading",
    question: "Can I hold positions overnight or over the weekend?",
    answer: "Yes. Positions can remain open while the referenced crypto market operates. Equity and risk limits continue to be monitored in real time.",
    rulesId: "fees-orders",
  },
  {
    id: "midnight-position",
    category: "Trading",
    question: "If my position is open past midnight UTC, which day does the profit count for?",
    answer: "Realized profit is assigned to the UTC date on which each position or partial fill closes. A qualifying Trading Day is assigned to the open date. Drawdown uses live equity and is not delayed by a date boundary.",
    rulesId: "rule-priority",
  },
  {
    id: "stop-loss",
    category: "Trading",
    question: "Do I have to use a stop loss?",
    answer: "No. A stop loss is not mandatory. The 4% Daily Loss circuit breaker and the 6% static floor still apply in real time, so you remain responsible for position sizing and risk controls.",
    rulesId: "daily-loss",
  },
  {
    id: "news-trading",
    category: "Trading",
    question: "Can I trade the news?",
    answer: "Opening or closing within ±2 minutes of a published high-impact event is prohibited. The in-app calendar identifies blocked windows. Affected PnL may be removed and repeated activity may trigger review.",
    rulesId: "fair-play",
  },
  {
    id: "bots-api",
    category: "Trading",
    question: "Can I use bots, EAs, or the API?",
    answer: "No. Orders must be placed manually through the official interface. Automated trading can close the account and cancel pending rewards.",
    rulesId: "fair-play",
  },
  {
    id: "trading-fees",
    category: "Trading",
    question: "Are trading fees charged?",
    answer: "Yes. Simulated trading fees are applied and shown in the order ticket. Current indicative settings are maker 0.02% and taker 0.05%. Funding payments are not currently applied, which is a disclosed simulation limitation.",
    rulesId: "fees-orders",
  },
  {
    id: "funded-result",
    category: "Funded Accounts",
    question: "What do I get when I pass?",
    answer: "After the passing result and applicable review, you receive a simulated funded account at the same size. There is no profit target or consistency requirement; the risk and fair-play rules continue to apply.",
    rulesId: "funded-rules",
  },
  {
    id: "funded-simulated",
    category: "Funded Accounts",
    question: "Is the funded account simulated too?",
    answer: "Yes. Funded accounts use the same simulated environment. Eligible rewards are real, discretionary performance-based payouts paid from company revenue in USDC.",
    rulesId: "simulation",
  },
  {
    id: "funded-rule-changes",
    category: "Funded Accounts",
    question: "What rules change on a funded account?",
    answer: "Total margin exposure is capped at 25% of balance, and a single position is capped at 2× balance notional. A Max Drawdown breach is permanent because funded accounts cannot be reset.",
    rulesId: "funded-rules",
  },
  {
    id: "multiple-funded",
    category: "Funded Accounts",
    question: "Can I have multiple funded accounts?",
    answer: "Yes, up to $200,000 of combined active funded allocation. Accounts must trade independently. Cross-account hedging or mirroring can close the accounts involved and cancel pending rewards.",
    rulesId: "funded-rules",
  },
  {
    id: "funded-inactivity",
    category: "Funded Accounts",
    question: "What happens if I stop trading?",
    answer: "An account with no trades for 30 days becomes inactive. The account status and any available recovery path are shown in the dashboard.",
    rulesId: "funded-rules",
  },
  {
    id: "profit-share",
    category: "Payouts",
    question: "How much of my profit do I keep?",
    answer: "The reward split starts at 80%, moves to 85% after 3 consecutive approved payouts, and reaches 90% after 6 consecutive approvals. A declined request resets the approval streak.",
    rulesId: "payouts",
  },
  {
    id: "first-payout",
    category: "Payouts",
    question: "When can I request my first payout?",
    answer: "After 7 trading days and 3 profitable days on the funded account, with at least $50 in eligible realized profit and all positions closed.",
    rulesId: "payouts",
  },
  {
    id: "payout-time",
    category: "Payouts",
    question: "How and when am I paid?",
    answer: "Approved rewards are paid in USDC. Requests enter a daily 09:00 UTC batch and are targeted for payment within 24 hours after approval. Each completed payout is recorded in Levli's internal ledger.",
    rulesId: "payouts",
  },
  {
    id: "withdrawable",
    category: "Payouts",
    question: "How is my withdrawable amount calculated?",
    answer: "Withdrawable amount equals realized profit minus amounts already paid and amounts currently on hold. Unrealized PnL is never withdrawable.",
    rulesId: "payouts",
  },
  {
    id: "auto-decline",
    category: "Payouts",
    question: "Why was my payout automatically declined?",
    answer: "Checks cover open positions, the $50 minimum, your tier cap, realized balance, drawdown-floor protection, first-payout eligibility, another pending request, and closed or inactive account status. The exact reason is displayed.",
    rulesId: "payouts",
  },
  {
    id: "payout-kyc",
    category: "Payouts",
    question: "Do I need KYC to withdraw?",
    answer: "Identity verification and recipient information may be required before payout approval, including whenever applicable sanctions or transfer rules require additional checks. The required step is shown before submission.",
    rulesId: "payouts",
  },
  {
    id: "fee-refund",
    category: "Payouts",
    question: "When do I get my entry fee back?",
    answer: "The evaluation fee is refunded with the first approved payout from the resulting funded account. Reset fees are not refunded.",
    rulesId: "payouts",
  },
  {
    id: "payout-floor",
    category: "Payouts",
    question: "Can a payout breach my drawdown floor?",
    answer: "No. The request is blocked if the resulting account balance would fall below the fixed drawdown floor.",
    rulesId: "payouts",
  },
  {
    id: "multiple-evaluations",
    category: "Fair Play & Security",
    question: "Can I have more than one Evaluation account at the same time?",
    answer: "Yes. Multiple Evaluation accounts are allowed when each account is traded independently.",
    rulesId: "fair-play",
  },
  {
    id: "cross-account",
    category: "Fair Play & Security",
    question: "What's not allowed across multiple accounts?",
    answer: "Opposite coordinated positions, copied or mirrored trades, shared devices used for account delegation, and credential sharing are prohibited. Accounts involved can be closed and pending rewards cancelled.",
    rulesId: "fair-play",
  },
  {
    id: "abuse-detection",
    category: "Fair Play & Security",
    question: "How do you detect abuse?",
    answer: "Automated signals may include cross-account correlation, device fingerprinting, and wallet-graph review. Borderline flags receive human review, and enforcement decisions are recorded with evidence and reasons.",
    rulesId: "fair-play",
  },
  {
    id: "account-sharing",
    category: "Fair Play & Security",
    question: "Can someone else trade my account?",
    answer: "No. Account sharing, delegation, or sale can close the account and cancel pending rewards.",
    rulesId: "fair-play",
  },
  {
    id: "rule-changes",
    category: "Fair Play & Security",
    question: "Will the rules change under me?",
    answer: "No. Rules are locked to the account at creation. Future changes apply only to accounts created after the change and are listed in the public Rules changelog.",
    rulesId: "changelog",
  },
  {
    id: "payment-methods",
    category: "Billing",
    question: "What payment methods do you accept?",
    answer: "Supported crypto payments are shown at checkout. Each Evaluation has a one-time fee with no recurring subscription charge.",
    rulesId: "account-sizes",
  },
  {
    id: "reset-cost",
    category: "Billing",
    question: "What does a reset cost?",
    answer: "Reset prices are $12 / $35 / $99 / $179 for the $2.5K / $10K / $25K / $50K Evaluations. A reset is available once within 7 days of failure.",
    rulesId: "resets",
  },
  {
    id: "refunds",
    category: "Billing",
    question: "Are fees refundable?",
    answer: "The evaluation fee is refunded with the first approved payout from the resulting funded account. Reset fees are non-refundable, and failed or abandoned Evaluations do not receive a fee refund.",
    rulesId: "account-sizes",
  },
];
